### ISSUE TITLE
Issue with latest version (0.11.12)

### ISSUE THREAD

**Issue by maicol07** [antfu/vite-plugin-pwa#199]
I have the following error when trying to start Vite dev server with the latest version (0.11.12):
```
failed to load config from C:\Users\Maicol\Documents\Projects\Web\openstamanager\osm_rewrite\vite.config.ts
error when starting dev server:
TypeError: Cannot read property 'disable' of undefinedents\Projects\Web\openstamanager\osm_rewrite
    at Object.get disabled [as disabled] (C:\Users\Maicol\Documents\Projects\Web\openstamanager\osm_rewrite\node_modules\.pnpm\vite-plugin-pwa@0.11.12\node_modules\vite-plugin-pwa\dist\index.js:617:27)
    at C:\Users\Maicol\Documents\Projects\Web\openstamanager\osm_rewrite\node_modules\.pnpm\deepmerge@4.2.2\node_modules\deepmerge\dist\cjs.js:94:59
    at Array.forEach (<anonymous>)
    at mergeObject (C:\Users\Maicol\Documents\Projects\Web\openstamanager\osm_rewrite\node_modules\.pnpm\deepmerge@4.2.2\node_modules\deepmerge\dist\cjs.js:86:18)
    at deepmerge (C:\Users\Maicol\Documents\Projects\Web\openstamanager\osm_rewrite\node_modules\.pnpm\deepmerge@4.2.2\node_modules\deepmerge\dist\cjs.js:117:10)
    at cloneUnlessOtherwiseSpecified (C:\Users\Maicol\Documents\Projects\Web\openstamanager\osm_rewrite\node_modules\.pnpm\deepmerge@4.2.2\node_modules\deepmerge\dist\cjs.js:34:5)
    at C:\Users\Maicol\Documents\Projects\Web\openstamanager\osm_rewrite\node_modules\.pnpm\deepmerge@4.2.2\node_modules\deepmerge\dist\cjs.js:94:23
    at Array.forEach (<anonymous>)
    at mergeObject (C:\Users\Maicol\Documents\Projects\Web\openstamanager\osm_rewrite\node_modules\.pnpm\deepmerge@4.2.2\node_modules\deepmerge\dist\cjs.js:86:18)
    at deepmerge (C:\Users\Maicol\Documents\Projects\Web\openstamanager\osm_rewrite\node_modules\.pnpm\deepmerge@4.2.2\node_modules\deepmerge\dist\cjs.js:117:10)
 ELIFECYCLE  Command failed with exit code 1.
```

Previous version (0.11.11) works fine

**Comment by userquin** [comment]
@maicol07 can you provide a minimal repro?

**Comment by maicol07** [comment]
@userquin this the repo I'm working on: [https://github.com/devcode-it/openstamanager/tree/3.x-dev](https://github.com/devcode-it/openstamanager/tree/3.x-dev) (branch 3.x-dev)

Currently, I've pinned Vite PWA to 0.11.11. You should be able to see the error by changing that to 0.11.12

**Comment by userquin** [comment]
@maicol07 here is no 3.x-dev, do you mean 3.x?

**Comment by maicol07** [comment]
> @maicol07 here is no 3.x-dev, do you mean 3.x?

Yes, sorry. I'm used to composer and npm branch names 😅

**Comment by userquin** [comment]
@maicol07 it seems there is some merge with pwa plugin options not yet resolved and so the error: the problem is that `osmConfig` will do a deep merge of the pwa plugin and we cannot do that since the options are resolved via Vite lifecyle.

If I just use `export default defineConfig().withPlugin(VitePWA({...}))` I have this another error on the client:
```js
LoginPage.tsx:28 Uncaught ReferenceError: React is not defined
    at LoginPage.view (LoginPage.tsx:28:5)
    at Function.callHook (render.js:30:16)
    at initComponent (render.js:155:45)
    at createComponent (render.js:160:3)
    at createNode (render.js:66:8)
    at createComponent (render.js:162:4)
    at createNode (render.js:66:8)
    at createNodes (render.js:50:5)
    at updateNodes (render.js:277:45)
    at render.js:964:4
view @ LoginPage.tsx:28
callHook @ render.js:30
initComponent @ render.js:155
createComponent @ render.js:160
createNode @ render.js:66
createComponent @ render.js:162
createNode @ render.js:66
createNodes @ render.js:50
updateNodes @ render.js:277
(anonymous) @ render.js:964
mount @ mount-redraw.js:45
setup @ app.ts:49
(anonymous) @ createInertiaApp.ts:34
```

**Comment by userquin** [comment]
@maicol07 previous error with pwa plugin `0.11.12` and just works, but opening the index page we get previous client error.

**Comment by maicol07** [comment]
Oh yeah, the trick was to use `withPlugin()` instead of the `plugins` array.

Thank you!
