### ISSUE TITLE
Failed to execute 'register' on 'ServiceWorkerContainer'

### ISSUE THREAD

**Issue by Aloento** [antfu/vite-plugin-pwa#266]
According to your guidance with React. Then, under dev, I got:

```
SW registration error TypeError: Failed to execute 'register' on 'ServiceWorkerContainer': Failed to read the 'type' property from 'RegistrationOptions': The provided value 'undefined' is not a valid enum value of type WorkerType.
    at Workbox.js:486:55
    at Workbox.js:565:16
    at v2.w.bn (Workbox.js:572:9)
    at Workbox.js:299:41
    at Workbox.js:551:9
    at v2.w.register (Workbox.js:551:14)
    at registerSW (react:46:8)
    at react:68:12
    at w (index.js:390:34)
    at p2 (index.js:139:12)
```

It's working on the production.
Maybe you don't have this:
navigator.serviceWorker.register('/sw.js', { scope: '/', _**type: 'module'**_ })

**Comment by userquin** [comment]
@Aloento can you provide a small repro or at lest your pwa plugin options?

**Comment by Aloento** [comment]
```ts
    VitePWA({
      base: '/',
      srcDir: "src",
      filename: "sw.ts",
      strategies: "injectManifest",
      manifest: {
        name: "MusiLand",
        short_name: "MusiLand",
        icons: [
          {
            src: "/android-chrome-192x192.png",
            sizes: "192x192",
            type: "image/png",
          },
          {
            src: "/android-chrome-512x512.png",
            sizes: "512x512",
            type: "image/png",
          },
        ],
        theme_color: "#ffffff",
        background_color: "#ffffff",
        start_url: ".",
        display: "standalone",
      },
    }),
```

**Comment by Aloento** [comment]
```ts
import { cleanupOutdatedCaches, createHandlerBoundToURL, precacheAndRoute } from 'workbox-precaching'
import { googleFontsCache, imageCache, pageCache, staticResourceCache } from 'workbox-recipes'
import { NavigationRoute, registerRoute } from 'workbox-routing'

declare const self: ServiceWorkerGlobalScope

self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING')
    self.skipWaiting()
})

// self.__WB_MANIFEST is default injection point
precacheAndRoute(self.__WB_MANIFEST)

// clean old assets
cleanupOutdatedCaches()

// to allow work offline
registerRoute(new NavigationRoute(createHandlerBoundToURL('index.html')))

pageCache();
googleFontsCache();
staticResourceCache();
imageCache();

```

**Comment by Aloento** [comment]
Then, No Service Worker enabled under dev.

**Comment by jetro4u** [comment]
I am having the same error when I followed the react/router example. My project uses jsx and not tsx. I got the error:
```
SW registration error TypeError: Failed to execute 'register' on 'ServiceWorkerContainer': Failed to read the 'type' property from 'RegistrationOptions': The provided value 'undefined' is not a valid enum value of type WorkerType.
    at Workbox.js:486:55
    at Workbox.js:565:16
    at v2.w.bn (Workbox.js:572:9)
    at Workbox.js:299:41
    at Workbox.js:551:9
    at v2.w.register (Workbox.js:551:14)
    at registerSW (react:46:8)
    at react:68:12
    at mountState (react-dom.development.js:15626:20)
```
Without setting up this update functionality, I can see the custom service worker in action in production. But the issue comes up when I tried to implement the prompt for update react/router example.
In my pwa plugin option I have:
```

    VitePWA({
      includeAssets: ['favicon.ico', 'robots.txt', '/assets/images/logos/apple-touch-icon.png'], 
      manifest: {
        name: 'xxxxxxxx',
        short_name: 'xxxxxx,
        description: "xxxxxxxxxx",
        display: "standalone",
        theme_color: '#000000',
        background_color: "#ffffff",
        icons: [
          {
            src: "favicon.ico",
            sizes: "64x64 32x32 24x24 16x16",
            type: "image/x-icon"
          },
          {
            src: "assets/images/logos/xxxxx-16.png",
            sizes: "16x16",
            type: "image/png"
          },
          {
            src: "assets/images/logos/xxxxx-32.png",
            sizes: "32x32",
            type: "image/png"
          },
          {
            src: "assets/images/logos/xxxxxxx-192.png",
            sizes: "192x192",
            type: "image/png"
          },
          {
            src: "assets/images/logos/xxxxx-512.png",
            sizes: "512x512",
            type: "image/png"
          },
          {
            src: "assets/images/logos/xxxxxx-512.png",
            sizes: "512x512",
            type: "image/png",
            purpose: 'any maskable'
          }
        ]
      },
      strategies: 'injectManifest',
      registerType: 'prompt',
      injectManifest: {
        globDirectory: 'dist/',
        globPatterns: ['**/*.{json,ico,svg,ttf,woff,css,js,html,txt,jpg,png,woff2,mjs}'],
        swDest: 'dist/sw.js',
        swSrc: 'sw.js',
        maximumFileSizeToCacheInBytes: 30000000
      },
      workbox: {
        importScripts: ["sw.js"]
      },
      devOptions: {
        enabled: true
        /* other options */  
      }
    })
```

**Comment by userquin** [comment]
have you added `WebWorker` to `tsconfig.json` file on `lib` entry? type module will work only on chromium based browsers (firefox will not support it)
```json
"lib": ["DOM", "DOM.Iterable", "ESNext", "WebWorker"],
```

**Comment by jetro4u** [comment]
In my case I am testing with chrome. By the way I added the WebWorker in lib entry but the issue persist?

**Comment by Aloento** [comment]
Me too

> 在我的情况下，我正在用chrome进行测试。顺便说一句，我在lib条目中添加了WebWorker，但问题仍然存在？

**Comment by Aloento** [comment]
> In my case I am testing with chrome. By the way I added the WebWorker in lib entry but the issue persist?

Me too

**Comment by jetro4u** [comment]
@Aloento when I added type: "module" to the devOptions, I got the error:
```
ReloadPrompt.jsx:15 SW registration error TypeError: Failed to register a ServiceWorker for scope ('http://localhost:3000/') with script ('http://localhost:3000/dev-sw.js?dev-sw'): A bad HTTP response code (404) was received when fetching the script.
```

**Comment by userquin** [comment]
the dev is only for sw testing not the pwa, I mean, it is only for sw logic testing, cannot work on offline for example.

I'm preparing the new release and I'll do some tests before releasing it, bbl with the results using the react example in this repo.

**Comment by userquin** [comment]
can you remove `node_modules/.vite` folder/directory and restart the dev server?

Testing with latest changes seems to work:

![imagen](https://user-images.githubusercontent.com/6311119/163855937-fa698fdc-adb8-465f-ae6e-4743a7deacdf.png)

**Comment by Aloento** [comment]
> the dev is only for sw testing not the pwa, I mean, it is only for sw logic testing, cannot work on offline for example.
> 
> I'm preparing the new release and I'll do some tests before releasing it, bbl with the results using the react example in this repo.

I know, I just say that browser cannot load SW. (always under the status of trying to install)
I will try your solution.

**Comment by Mansurkhoja** [comment]
> > the dev is only for sw testing not the pwa, I mean, it is only for sw logic testing, cannot work on offline for example.
> > I'm preparing the new release and I'll do some tests before releasing it, bbl with the results using the react example in this repo.
> 
> I know, I just say that browser cannot load SW. (always under the status of trying to install) I will try your solution.

same problem, 
did you find solution?

**Comment by userquin** [comment]
@Mansurkhoja open a new issue with a reproduction, we don't usually check closed issues
