### ISSUE TITLE
Cannot read properties of undefined (reading 'disable')

### ISSUE THREAD

**Issue by lindsaykwardell** [antfu/vite-plugin-pwa#320]
When attempting to use this plugin from within Astro, the environment fails to start. Below is the stack trace of the error:

```
error   Cannot read properties of undefined (reading 'disable')
    at get disabled [as disabled] (/home/projects/github-vqbp9y/node_modules/vite-plugin-pwa/dist/index.js:741:27)
    at eval (/home/projects/github-vqbp9y/node_modules/deepmerge/dist/cjs.js:94:59)
    at Array.forEach (<anonymous>)
    at mergeObject (/home/projects/github-vqbp9y/node_modules/deepmerge/dist/cjs.js:86:18)
    at deepmerge (/home/projects/github-vqbp9y/node_modules/deepmerge/dist/cjs.js:117:10)
    at cloneUnlessOtherwiseSpecified (/home/projects/github-vqbp9y/node_modules/deepmerge/dist/cjs.js:34:5)
    at eval (/home/projects/github-vqbp9y/node_modules/deepmerge/dist/cjs.js:94:23)
    at Array.forEach (<anonymous>)
    at mergeObject (/home/projects/github-vqbp9y/node_modules/deepmerge/dist/cjs.js:86:18)
    at deepmerge (/home/projects/github-vqbp9y/node_modules/deepmerge/dist/cjs.js:117:10)
```

Step to reproduce:
1. Set up a fresh Astro site (any template).
2. Install vite-plugin-pwa
3. Configure the plugin with the basics, as below:

```js
import { defineConfig } from 'astro/config';

import { VitePWA } from 'vite-plugin-pwa';

// https://astro.build/config
export default defineConfig({
  vite: {
    plugins: [VitePWA()],
  },
});
```

4. Attempt to run or build the site (`npm run dev` or `npm run build`). Neither will work, and node will throw the above error.

Reproduction link: https://stackblitz.com/edit/github-vqbp9y?file=astro.config.mjs

**Comment by userquin** [comment]
@lindsaykwardell we are working to add support on Astro repo, I have a draft PR here https://github.com/withastro/astro/pull/3428

Astro is trying to make a deep merge of each pwa plugin before Vite resolves the configuration, and so the rollup intercomunication api exposed will fail when resolving the disable prop vía its getter.
https://github.com/antfu/vite-plugin-pwa/blob/main/src/index.ts#L93
