### ISSUE TITLE
Couldn't find configuration for either precaching or runtime caching.

### ISSUE THREAD

**Issue by xieyezi** [antfu/vite-plugin-pwa#71]
This is my `devDependencies`:
```json
  "devDependencies": {
    "@better-scroll/core": "^2.3.1",
    "@commitlint/cli": "^12.1.4",
    "@commitlint/config-angular": "^12.1.4",
    "@types/axios": "^0.14.0",
    "@types/node": "^15.6.0",
    "@vitejs/plugin-vue": "^1.2.2",
    "@vue/compiler-sfc": "^3.0.5",
    "@vueuse/core": "^4.11.0",
    "autoprefixer": "^10.2.5",
    "axios": "^0.21.1",
    "commitizen": "^4.2.3",
    "commitlint-config-cz": "^0.13.2",
    "cz-customizable": "^6.3.0",
    "eslint": "^7.27.0",
    "eslint-plugin-prettier": "^3.4.0",
    "husky": "^6.0.0",
    "lint-staged": "^10.5.3",
    "postcss": "^8.3.0",
    "prettier": "^2.2.1",
    "tailwindcss": "^2.1.2",
    "typescript": "^4.1.3",
    "vite": "^2.3.3",
    "vite-plugin-pwa": "^0.7.3",
    "vite-plugin-style-import": "^0.10.0",
    "vue-tsc": "^0.0.24",
    "xieyezi-storage": "^1.0.4"
  },
```
And this is my `vite.config.ts`:
```ts
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import styleImport from 'vite-plugin-style-import';
import { resolve } from 'path'
import { VitePWA } from 'vite-plugin-pwa'


// https://vitejs.dev/config/
export default defineConfig({
  resolve: {
    alias: {
      "@src": resolve(__dirname, "./src"),
      "@assets": resolve(__dirname, "./src/assets"),
      "@components": resolve(__dirname, "./src/components"),
      "@uitl": resolve(__dirname, "./src/uitl")
    }
  },
  plugins: [
    vue(),
    styleImport({
      libs: [
        {
          libraryName: 'vant',
          esModule: true,
          resolveStyle: (name) => `vant/es/${name}/style`,
        },
      ],
    }),
    VitePWA({
      outDir: '.vue3-shopping-airi/dist',
      manifest: {
        name: 'Vue3-AiRi',
        short_name: 'AiRi',
        theme_color: '#ffffff',
        icons: [
          {
            src: '/pwa-192x192.png',
            sizes: '192x192',
            type: 'image/png',
          },
          {
            src: '/pwa-512x512.png',
            sizes: '512x512',
            type: 'image/png',
          },
        ],
      },
    }),
  ],
  server: {
    proxy: {
      '/api': {
        target: 'http://xieyezi.com:9003/mock/11/airi',
        changeOrigin: true,
        rewrite: (path: string) => path.replace(/^\/api/, '')
      }
    }
  }
})

```
When I run `yarn build`(`"build": "vue-tsc --noEmit && vite build"`), but I get this error:
```
Error: Couldn't find configuration for either precaching or runtime caching. Please ensure that the various glob options are set to match one or more files, and/or configure the runtimeCaching option.
```
In fact ,I have cat #39 , but I dont't know how to reslove this.

So can you provide some help?

Thanks!

**Comment by xieyezi** [comment]
And my repo link: https://github.com/xieyezi/vue3-shopping-airi/blob/18078e0af4401764f5fd4d7963775a57290ce5bc/vite.config.ts#L29

**Comment by userquin** [comment]
@xieyezi do the following:
- remove `dist` folder
- `yarn upgrade vite-plugin-pwa -L`
- `yarn build`

With `0.7.3` version `yarn build` fails:
```shell
F:\work\projects\quini\GitHub\vue3-shopping-airi>yarn build
yarn run v1.22.10
warning package.json: No license field
$ vue-tsc --noEmit && vite build
vite v2.3.3 building for production...
transforming (31) src\assets\images\home\loading.png
warn - Tailwind is not purging unused styles because no template paths have been provided.
warn - If you have manually configured PurgeCSS outside of Tailwind or are deliberately not removing unused styles, set `purge: false` in your Tailwind config file to silence this warning.
warn - https://tailwindcss.com/docs/controlling-file-size/#removing-unused-css
✓ 402 modules transformed.
dist/assets/loading.225d9e08.png   4.04kb
dist/index.html                    0.59kb
dist/manifest.webmanifest          0.29kb
dist/registerSW.js                 0.13kb
dist/assets/index.e73db258.css     5522.28kb / brotli: skipped (large chunk)
dist/assets/index.68a96c14.js      1.55kb / brotli: 0.70kb
dist/assets/Login.99efd030.js      9.01kb / brotli: 5.96kb
dist/assets/Index.b8ebc931.css     0.52kb / brotli: 0.21kb
dist/assets/Login.80e60b67.css     2.47kb / brotli: 0.59kb
dist/assets/vendor.aa5d96b7.css    49.40kb / brotli: 25.94kb
dist/assets/Index.d72d5d30.js      73.77kb / brotli: 24.18kb
dist/assets/vendor.178f9aaf.js     111.59kb / brotli: 37.61kb
error during build:
Error: Couldn't find configuration for either precaching or runtime caching. Please ensure that the various glob options are set to match one or more files, and/or configure the runtimeCaching option.
    at module.exports (F:\work\projects\quini\GitHub\vue3-shopping-airi\node_modules\workbox-build\build\lib\populate-sw-template.js:41:11)
    at module.exports (F:\work\projects\quini\GitHub\vue3-shopping-airi\node_modules\workbox-build\build\lib\write-sw-using-default-template.js:50:25)
    at async generateSW (F:\work\projects\quini\GitHub\vue3-shopping-airi\node_modules\workbox-build\build\generate-sw.js:229:21)
    at async Object.closeBundle (F:\work\projects\quini\GitHub\vue3-shopping-airi\node_modules\vite-plugin-pwa\dist\index.js:329:13)
    at async Promise.all (index 0)
    at async Object.close (F:\work\projects\quini\GitHub\vue3-shopping-airi\node_modules\vite\node_modules\rollup\dist\shared\rollup.js:20593:13)
    at async Promise.all (index 0)
    at async build (F:\work\projects\quini\GitHub\vue3-shopping-airi\node_modules\vite\dist\node\chunks\dep-e9a16784.js:44738:13)
    at async CAC.<anonymous> (F:\work\projects\quini\GitHub\vue3-shopping-airi\node_modules\vite\dist\node\cli.js:13925:9)
error 
```
after upgrading to new version `0.8.0` and building again (removing `dist` folder):
```shell
F:\work\projects\quini\GitHub\vue3-shopping-airi>yarn upgrade vite-plugin-pwa -L
yarn upgrade v1.22.10
warning package.json: No license field
warning vue3-shopping-airi@0.0.0: No license field
warning vue3-shopping-airi@0.0.0: No license field
warning vue3-shopping-airi@0.0.0: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "win32" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > genji-es@1.0.2" has unmet peer dependency "@vue/reactivity@^3.0.11".
warning " > commitlint-config-cz@0.13.2" has incorrect peer dependency "@commitlint/cli@^7.0.0 || ^8.0.0 || ^9.0.0".
warning "vite-plugin-style-import > @rollup/pluginutils@4.1.0" has unmet peer dependency "rollup@^1.20.0||^2.0.0".
[4/4] Rebuilding all packages...
success Saved lockfile.
warning vue3-shopping-airi@0.0.0: No license field
success Saved 1 new dependency.
info Direct dependencies
└─ vite-plugin-pwa@0.8.0
info All dependencies
└─ vite-plugin-pwa@0.8.0
Done in 2.52s.

F:\work\projects\quini\GitHub\vue3-shopping-airi>yarn build
yarn run v1.22.10
warning package.json: No license field
$ vue-tsc --noEmit && vite build
vite v2.3.3 building for production...
transforming (28) src\views\home\Home.vue
warn - Tailwind is not purging unused styles because no template paths have been provided.
warn - If you have manually configured PurgeCSS outside of Tailwind or are deliberately not removing unused styles, set `purge: false` in your Tailwind config file to silence this warning.
warn - https://tailwindcss.com/docs/controlling-file-size/#removing-unused-css
✓ 402 modules transformed.
dist/assets/loading.225d9e08.png   4.04kb
dist/index.html                    0.59kb
dist/manifest.webmanifest          0.29kb
dist/registerSW.js                 0.13kb
dist/assets/index.e73db258.css     5522.28kb / brotli: skipped (large chunk)
dist/assets/index.68a96c14.js      1.55kb / brotli: 0.70kb
dist/assets/Login.99efd030.js      9.01kb / brotli: 5.96kb
dist/assets/Index.b8ebc931.css     0.52kb / brotli: 0.21kb
dist/assets/Login.80e60b67.css     2.47kb / brotli: 0.59kb
dist/assets/vendor.aa5d96b7.css    49.40kb / brotli: 25.94kb
dist/assets/Index.d72d5d30.js      73.77kb / brotli: 24.18kb
dist/assets/vendor.178f9aaf.js     111.59kb / brotli: 37.61kb
Done in 30.68s.
```

**Comment by xieyezi** [comment]
@userquin Oh,thanks a lot! It's useful!❤️
