### ISSUE TITLE
App cannot find a place to inject manifest

### ISSUE THREAD

**Issue by NicolaSpadari** [antfu/vite-plugin-pwa#91]
I'm trying to deploy my app on Netlify as an installable PWA, but everytime it compiles I get this error:
```
6:03:00 PM: error during build:
6:03:00 PM: Error: Unable to find a place to inject the manifest. This is likely because swSrc and swDest are configured to the same file. Please ensure that your swSrc file contains the following: self.__WB_MANIFEST
6:03:00 PM:     at injectManifest (/opt/build/repo/node_modules/workbox-build/build/inject-manifest.js:160:13)
6:03:00 PM:     at async generateInjectManifest (/opt/build/repo/node_modules/vite-plugin-pwa/dist/index.js:103:3)
6:03:00 PM:     at async Object.closeBundle (/opt/build/repo/node_modules/vite-plugin-pwa/dist/index.js:438:13)
6:03:00 PM:     at async Promise.all (index 0)
6:03:00 PM:     at async Object.close (/opt/build/repo/node_modules/rollup/dist/shared/rollup.js:20947:13)
6:03:00 PM:     at async Promise.all (index 0)
6:03:00 PM:     at async build (/opt/build/repo/node_modules/vite/dist/node/chunks/dep-f2b4ca46.js:51462:13)
6:03:00 PM:     at async CAC.<anonymous> (/opt/build/repo/node_modules/vite/dist/node/cli.js:13999:9)
```

I followed your `vue-basic-inject-manifest` example, here is my pwa in the `vite.config.js` file:
```
VitePWA({
    mode: "development", // <-- also tried without this
    srcDir: "src",
    filename: "sw.js",
    base: "/",
    strategies: "injectManifest",
    includeAssets: ["/favicon.ico"],
    manifest: {
        name: "Food Exp Tracker",
        short_name: "Exp Tracker",
        theme_color: "#222226",
        background_color: "#222226",
        display: "standalone",
        icons: [
            {
                src: "/android-chrome-192x192.png",
                sizes: "192x192",
                type: "image/png",
            },
            {
                src: "/android-chrome-512x512.png",
                sizes: "512x512",
                type: "image/png",
            },
        ],
    },
}),
```

Also, adding `workboxOptions` as it follows doesn't help:
```
workboxOptions: {
    swSrc: "src/sw.js",
    swDest: "sw.js",
    exclude: [/\.map$/, /_redirects/]
}
```

my `sw.js` file (located in `/src`):
```
import { precacheAndRoute } from "workbox-precaching";

let self;

self.addEventListener("message", (event) => {
    if (event.data && event.data.type === "SKIP_WAITING") self.skipWaiting();
});

precacheAndRoute(self.__WB_MANIFEST);
```

And yes, `workbox-precaching` is installed as dev dependency (ver. 6.1.5).

Can you help me find out what's wrong with this? It's a simple single page app, no router, no store, without the `injectManifest` the app works but it isn't installable.

**Comment by userquin** [comment]
@NicolaSpadari since you are using `javascript` remove `let self;` from your`sw.js` file.

**Comment by liho98** [comment]
Same issue here, @userquin  why r u closing this?

**Comment by userquin** [comment]
@liho98 the problem reporte originally fails because the sw is overriding the self scope and so it fails.

If your sw.js resides in public dir then the error is other since it Will be copy by vite and then thinolugin will skip it generation.
